import Navbar from "@/src/components/Navbar";
import Footer from "@/src/components/Footer";
import ClientLayout from "./ClientLayout"; // ← import ini
import "./globals.css";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
    weight: ['400', '600', '700'],
    subsets: ['latin'],
    variable: "--font-poppins"
});

export const metadata = {
    title: "Samarinda Hash House Harriers",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html
            lang="en"
            className={`h-full antialiased ${poppins.className}`}
        >
            <body className="min-h-full flex flex-col text-neutral-text">
                <ClientLayout>
                    <Navbar />
                    {children}
                    <Footer />
                </ClientLayout>
            </body>
        </html>
    );
}